---
title: "buffer_coords_biomes"
author: "Carla"
date: "2022-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages 

```{r message=TRUE, warning=FALSE, paged.print = FALSE}
rm(list=ls())
library("tidyverse") # loads packages tidyr, ggplot2 and dplyr
library("sf") # load sf package used for spatial data
library ("mapview") # package to create maps
#library ("raster") # package to work with rasters
library("rlist") #to work with lists
library("terra")

theme_set(theme_minimal(base_size = 14)) # set ggplot theme 
```

# Working directories 
``` {r message=TRUE, warning=TRUE, paged.print=FALSE}

setwd(here::here())

plots <- file.path(here::here("plots")) # species where to save plots

data.output <- file.path(here::here("output")) # specifies where to save outputs

data.input <- file.path(here::here("data-raw","r-raw")) 

```


# Getting the data 

``` {r data input}
study_area_size_data <- read.csv2(paste0(data.input,"/coords_study_area_14102022.csv"), header=TRUE, sep=";", dec = ".")

``` 

# View data

``` {r visualise data}
summary(study_area_size_data)
str(study_area_size_data)

```

# Transform data

``` {r transform into multipoint data}
#extr cting the study area size and taking out the nas 
study_area_size_data_no_nas <- study_area_size_data %>% 
  na.omit() %>%
 dplyr:: select(longitude, latitude) %>%
  tibble::rowid_to_column("id")

# calculating the radius of the buffer based on the study area size
buffer_size <- study_area_size_data %>%
  na.omit() %>%
  mutate(radius=(sqrt(study_area_size/pi) * 1000)) %>% # *1000 to convert to km 
  dplyr::select(radius)

#transforming the coordinates as spatial object
coords <- st_as_sf(study_area_size_data_no_nas, coords=c("longitude","latitude"), crs=4326)

```

# Help functions 
```{r functions to help }
#function to transform the latitude longitute projection of each poitns into the right UTM
lonlat2UTM = function(lonlat) {
  utm = (floor((lonlat[1] + 180) / 6) %% 60) + 1
  if(lonlat[2] > 0) {
    utm + 32600
  } else{
    utm + 32700
  }
}

#to transform in the right projection
transform_list <- function(list, crs_dataframe){ 
  x <- list(0)
  for (i in 1: length(crs_dataframe))
    x[[i]] <- st_transform(list[[i]], crs_dataframe[i])
  return(x)
  
}


# to create buffers based on a list of spatial objects
buffer_list <- function(list, buffer_size_dataframe){
  y <- list(0)
  for (i in 1: nrow(buffer_size_dataframe))
    y[[i]] <- st_buffer(list[[i]], buffer_size_dataframe[i,])
  return(y)

}

```

# extracting the proper UTM for each study point
```{r extract the UTM}
#take out the coordinates of the points
coordinates2<- cbind(study_area_size_data_no_nas$longitude, study_area_size_data_no_nas$latitude)

#transforms the coordinates into UTM
coordinatesUTM <- apply(coordinates2, 1, lonlat2UTM)


#creates a list of spatial objects based on their id 
ncSplit <- split(coords, f = coords[["id"]])

#using the function to st_transform each element of the list with their corresponding UTM
list_UTM_points <- transform_list(ncSplit, coordinatesUTM)
```

#Create the buffers and reproject them on a lat long system
```{r buffers}
# Create a list of buffers with their respective radius
buf_proj <- buffer_list(list_UTM_points, buffer_size)

# Retransform the whole shablam into a latitude longitude coordinate system
buf_latlong <- lapply(buf_proj, st_transform, 4326)

#recombining the hwole thing
combined <- list.rbind(buf_latlong)

```

#plot the buffers 
```{r plot buffers }

combined %>% 
  ggplot() + 
  geom_sf(lwd = 0.1)

mapview(combined)
```

# Load the raster map

``` {r load raster}
map_raster <- terra::rast(paste0(here::here("data-raw","geo-raw"),"/biomes_wgs.tif"))

str(map_raster)
plot(map_raster)
```                

# Extracting values from raster

``` {r Extracting values from raster}
buffer_new_projection <- combined %>%
  st_transform(crs = crs(map_raster))

extracted_values_mean_biomes <- raster::extract(map_raster, buffer_new_projection,fun=mean, na.rm=TRUE)

extracted_values_mean_biomes 

saveRDS(extracted_values_mean_biomes,paste0(data.output,"/data-proc/extracted_values_mean_biomes",Sys.Date(),".rds"))
```

# Plot buffers with biomes

``` {r plot buffers}
combined_buffer_biomes <- cbind(buffer_new_projection,extracted_values_mean_biomes)
mapview(combined_buffer_biomes, zcol="biomes_wgs")

dataframe_combined_buffer_biomes <- study_area_size_data %>%
  na.omit() %>%
  cbind(combined_buffer_biomes)

saveRDS(dataframe_combined_buffer_biomes,paste0(data.output,"/data-proc/dataframe_combined_buffer_biomes",Sys.Date(),".rds"))
```
