---
title: "mortality_regression"
author: "Carla"
date: '2022-06-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages 

```{r message=TRUE, warning=FALSE, paged.print = FALSE}
rm(list=ls())
library("tidyverse") # loads packages tidyr, ggplot2 and dplyr
library("sf") # load sf package used for spatial data
library ("mapview") # package to create maps
library ("raster") # package to work with rasters
library("lme4") # package for linear regression
theme_set(theme_minimal(base_size = 14)) # set ggplot theme 
```

# Working directories 
``` {r message=TRUE, warning=TRUE, paged.print=FALSE}

setwd(here::here())

plots <- file.path(here::here("plots")) # species where to save plots

data.output <- file.path(here::here("output")) # specifies where to save outputs

data.input <- file.path(here::here("data-raw","r-raw")) 

```

# Load the data

``` {r in the data}

mortality_data <- read.csv2(paste0(data.input,"/MortalityRatesWolfReview21062022_JL_ID.csv"), header=TRUE, sep=";", dec = ".")

human_footprint <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_hfp2022-06-21.rds"))
```

# Create a new table

``` {r mortality hfp}
mortality_hfp_ID <- mortality_data %>%
  left_join(human_footprint,by="study_ID") %>%
  dplyr::select(study_ID,calculated_rate,extracted_values_mean_hfp) %>%
  rename(ID=study_ID,mortality=calculated_rate,hfp=extracted_values_mean_hfp) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(hfp_standard=scale(hfp))
```
# Linear regression

``` {r linear regression}
lm1 <- lm(mortality~hfp_standard,data=mortality_hfp_ID)

plot(lm1)

print(lm1)

summary(lm1)

lm2 <- lmer(mortality~(1|ID)+hfp_standard,data=mortality_hfp_ID)

summary(lm2)
```

