---
title: "lm_mortality"
author: "Carla"
date: "2022-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages 

```{r message=TRUE, warning=FALSE, paged.print = FALSE}
rm(list=ls())
library("tidyverse") # loads packages tidyr, ggplot2 and dplyr
library("sf") # load sf package used for spatial data
library ("mapview") # package to create maps
library ("raster") # package to work with rasters
library("lme4") # package for linear regression
theme_set(theme_minimal(base_size = 14)) # set ggplot theme 
```

# Working directories 
``` {r message=TRUE, warning=TRUE, paged.print=FALSE}

setwd(here::here())

plots <- file.path(here::here("plots")) # species where to save plots

data.output <- file.path(here::here("output")) # specifies where to save outputs

data.input <- file.path(here::here("data-raw","r-raw")) 

```

# Load the data

``` {r in the data}

mortality_data <- read.csv2(paste0(data.input,"/mortality_13112022.csv"), header=TRUE, sep=";", dec = ".")

forest_loss <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_forloss2022-11-11.rds"))

ecoregions <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_eco2022-11-10.rds"))

devthreats <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_dev_threat2022-11-10.rds"))

protected_areas <-readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_wdpa2022-11-10.rds"))

accessibility <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_access2022-11-10.rds"))

biomes <- readRDS(paste0(data.output, "/data-proc/dataframe_combined_buffer_biomes2022-11-13.rds"))
```

# Create a new table

``` {r mortality forest loss}

# forest loss
mortality_forloss_ID <- mortality_data %>%
  left_join(forest_loss,by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,forloss_drivers_prj,country,age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate,forloss=forloss_drivers_prj) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(forloss_standard=scale(forloss)) 
  
mortality_forloss_ID2 <- mortality_forloss_ID

head(mortality_forloss_ID2)

mortality_forloss_ID2$age_class <- as.factor(mortality_forloss_ID2$age_class)

class(mortality_forloss_ID2$age_class)

head(mortality_forloss_ID2)

# ecoregions
eco_mort_ID <- mortality_data %>%
  left_join(ecoregions, by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,ecoregions_wgs,country, age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate, eco=ecoregions_wgs) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(eco_standard=scale(eco))

# development threats

devthreat_mort_ID <- mortality_data %>%
  left_join(devthreats, by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,dev_threat_prj_maskf,country,age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate, devt=dev_threat_prj_maskf) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(devt_standard=scale(devt))

# protected areas 

wdpa_mort_ID <- mortality_data %>%
  left_join(protected_areas, by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,wdpa_bin_prj,country,age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate, wdpa=wdpa_bin_prj) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(wdpa_standard=scale(wdpa))

# accessibility 

access_mort_ID <- mortality_data %>%
  left_join(accessibility, by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,accessibility,country,age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate, access=accessibility) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(access_standard=scale(access))

# biomes

bio_mort_ID <- mortality_data %>%
  left_join(biomes, by="study_ID") %>%
  dplyr::select(study_ID,calc_surv_rate,biomes_wgs,country,age_class) %>%
  rename(ID=study_ID,mortality=calc_surv_rate, bio=biomes_wgs) %>%
  mutate(mortality=as.numeric(mortality)) %>%
  mutate(bio_standard=scale(bio))


```
# Linear regression

``` {r linear regression}
# forest loss
lmforloss<- glm(mortality~forloss_standard,data=mortality_forloss_ID, family="binomial")

plot(lmforloss)

print(lmforloss)

summary(lmforloss)

# ID as random effect

lmforloss2 <- glmer(mortality~(1|ID)+forloss_standard,data=mortality_forloss_ID, "binomial")

summary(lmforloss2)

# country as random effect

lmforlosscountry <-glmer(mortality~(1|country)+forloss_standard, data=mortality_forloss_ID, family="binomial")

plot(lmforlosscountry)

print(lmforlosscountry)

summary(lmforlosscountry)

# age class as random effect

lmforlossage <-glmer(mortality~(1|age_class)+forloss_standard, data=mortality_forloss_ID, family="binomial")

plot(lmforlossage)

print(lmforlossage)

summary(lmforlossage)


# age class as factor 
lmforlossage2 <-glmer(mortality~(1|age_class)+forloss_standard, data=mortality_forloss_ID2, family="binomial")

plot(lmforlossage2)

print(lmforlossage2)

summary(lmforlossage2)

# ecoregions
lmeco<- glm(mortality~eco_standard,data=eco_mort_ID, family="binomial")

plot(lmeco)

print(lmeco)

summary(lmeco)

lmeco2 <- glmer(mortality~(1|ID)+eco_standard,data=eco_mort_ID, family="binomial")

summary(lmeco2)

# random effect country

lmecocountry <- glmer(mortality~(1|country)+eco_standard, data=eco_mort_ID, family = "binomial")

summary(lmecocountry)

# random effect age class

lmecoage <- glmer(mortality~(1|age_class)+eco_standard, data=eco_mort_ID, family = "binomial")

summary(lmecoage)

# development threats
lmdevt<- glm(mortality~devt_standard,data=devthreat_mort_ID, family="binomial")

plot(lmdevt)

print(lmdevt)

summary(lmdevt)

lmdevt2 <- glmer(mortality~(1|ID)+devt_standard,data=devthreat_mort_ID, family="binomial")

summary(lmeco2)

# random effect country

lmdevtcountry <- glmer(mortality~(1|country)+devt_standard,data=devthreat_mort_ID, family="binomial")

summary(lmdevtcountry)

# random effect age class

lmdevtage <- glmer(mortality~(1|age_class)+devt_standard,data=devthreat_mort_ID, family="binomial")

summary(lmdevtage) # 0.06503 could be significant once age classes are properly sorted out

# protected areas
lmpas<- glm(mortality~wdpa_standard,data=wdpa_mort_ID, family="binomial")

plot(lmpas)

print(lmpas)

summary(lmpas)

lmpas2 <- glmer(mortality~(1|ID)+wdpa_standard,data=wdpa_mort_ID, family="binomial")

summary(lmpas)

# country as random effect 

countrywdpa <- glmer(mortality~(1|country)+wdpa_standard, data=wdpa_mort_ID, family="binomial")

summary(countrywdpa)

# age class as random effect

lmagewdpa <- glmer(mortality~(1|age_class)+wdpa_standard, data=wdpa_mort_ID, family="binomial")

summary(lmagewdpa)



# accessibility

lmacc<- glm(mortality~access_standard,data=access_mort_ID, family ="binomial")

plot(lmacc)

print(lmacc)

summary(lmacc)

lmacc2 <- glmer(mortality~(1|ID)+access_standard,data=access_mort_ID, family ="binomial")

summary(lmacc)

# country as random effect
lmacccountry <- glmer(mortality~(1|country)+access_standard,data=access_mort_ID, family ="binomial")

summary(lmacccountry)

# age class as random effect

lmaccage <- glmer(mortality~(1|age_class)+access_standard,data=access_mort_ID, family ="binomial")

summary(lmaccage)

# biomes

lmbio<- glm(mortality~bio_standard,data=bio_mort_ID, family="binomial")

plot(lmbio)

print(lmbio)

summary(lmbio)


lmbio2 <- glmer(mortality~(1|ID)+bio_standard,data=bio_mort_ID, family="binomial")

summary(lmbio2)

# country as random effect

lmbiocountry <- glmer(mortality~(1|country)+bio_standard,data=bio_mort_ID, family="binomial")

summary(lmbiocountry)

# age class as random effect

lmbioage<- glmer(mortality~(1|age_class)+bio_standard,data=bio_mort_ID, family="binomial")

summary(lmbiocountry)

```

